### ISSUE TITLE
Change to `AsyncPackage`

### ISSUE THREAD

**Issue by zooba** [zooba/indentguide#10]
I can't publish a new release for VS 2019 until we switch to AsyncPackage instead of Package.

A first attempt shows that there are a lot of assumptions about synchronous initialization throughout the code. It'll be big and intrusive.

That said, VS 2019 still seems to work okay, so if you want it you can use the attached VSIX. This is just a Marketplace limitation.

[IndentGuide v16.vsix.zip](https://github.com/zooba/indentguide/files/3183429/IndentGuide.v16.vsix.zip)

**Comment by Thieum** [comment]
@zooba I'll give it a try.

**Comment by prakharmody1996** [comment]
> I can't publish a new release for VS 2019 until we switch to AsyncPackage instead of Package.
> 
> A first attempt shows that there are a lot of assumptions about synchronous initialization throughout the code. It'll be big and intrusive.
> 
> That said, VS 2019 still seems to work okay, so if you want it you can use the attached VSIX. This is just a Marketplace limitation.
> 
> [IndentGuide v16.vsix.zip](https://github.com/zooba/indentguide/files/3183429/IndentGuide.v16.vsix.zip)

Silly question. Where exactly are the contents of the zip to be put. Tried it in
"C:\Users\PrakharMody\AppData\Local\Microsoft\VisualStudio\16.0_fe133630\Extensions" but does not detect in visual studio 2019.

**Comment by GoldenCrystal** [comment]
You should simply drop the `.zip` extension (e.g. in PowerShell `Rename-Item IndentGuide.v16.vsix.zip IndentGuide.v16.vsix`) and install the `.vsix` like another extension.

**Comment by Thieum** [comment]
@Zooba I've been doing some testing and I'm not sure how to handle the AddService / GetService for the IndentGuideService

```
 // Adds a service on the background thread
            AddService(typeof(IndentGuideService), CreateIndentGuideServiceAsync);
        }

        private async System.Threading.Tasks.Task<object> CreateIndentGuideServiceAsync(IAsyncServiceContainer container, CancellationToken cancellationToken, Type serviceType)
        {
            Service = new IndentGuideService(this);
            await System.Threading.Tasks.Task.Run(() =>
           {
               Service.Upgrade();
               Service.Load();
           });
            return Service;
        }
```

The add is called but the async Creation never gets called. The doc is really not clear about what can trigger the creation, and there are no clear example of what to do. The create is supposed to be called on the first get, but it doesn't.

Do you have any example of what is supposed to be done across the app to get the Service?

What I've tried is commited [there](https://github.com/Thieum/indentguide/commit/81f8b805b46892c6947ec3bd2d05fa50a3b2665d)

Any guidance would be really appreciated.

**Comment by Thieum** [comment]
Found a working example [here](https://github.com/iccfish/indent-guides-mod). I tested it in VS2019, need to test it in VS2017. Seems like a hack but it works.

**Comment by JordyWells** [comment]
Is the PR related to this going to be completed soon?
As far as I can tell its just waiting to be merged? Would love to have this working in VS 2019

**Comment by Thieum** [comment]
@JordyWells I completed the PR and tested it in VS2017 / 2019 . Waiting for @zooba (I think he's been quite busy with the [python environment improvements for win10](https://devblogs.microsoft.com/python/python-in-the-windows-10-may-2019-update/)) for merge or review for improvements. You can build the extension from source (either the current version or the PR will work in VS2019) if you want to use it until it is published on the marketplace.

**Comment by zooba** [comment]
Sorry for taking my time on this - I have plenty of things that I'm busy with these days :)

I merged the changes so at least they're in there. It sounds like at least a few people are happy with it, but I'll run it through a bit of my own testing (hopefully next week) before putting it up on the gallery.
