### ISSUE TITLE
Add tag for 15.0 Release for VS 2010-2015 users

### ISSUE THREAD

**Issue by amelvill-umich** [zooba/indentguide#14]
On my fork I just added this tag https://github.com/amelvill-umich/indentguide/releases/tag/v15.0 , it doesn't integrate with CI but it does build manually.

I would recommend adding this tag for users that are stuck on VS 2010-2015.

**Comment by zooba** [comment]
So I've made the tag, but the latest build I can find that was released is 15.0b4. But that's identical apart from the version number, so it should be okay.

https://github.com/zooba/indentguide/releases/tag/v15.0

**Comment by freemedom** [comment]
https://github.com/zooba/indentguide/releases/tag/v15.0

This doesn't work with VS 2010, I found one that works https://github.com/freemedom/-/blob/main/indentguide.vsix
