### ISSUE TITLE
Is it possible to apply different color for the indent line?

### ISSUE THREAD

**Issue by xiedongweo** [zooba/indentguide#15]
Is it possible to apply different color for the indent line?

**Comment by Kiefy** [comment]
Yes, look in: **Options** > **Indent Guides**.

![Indent Guide Options](https://i.imgur.com/o1yqhC6.png)

It's the most configurable Indent Guide system I've ever seen, though unfortunately, it has an issue https://github.com/zooba/indentguide/issues/16 that needs to be fixed before I can use it.
